#!/bin/bash

# create the function to log messages
# first  parameter must be the script name
# second parameter must be the log level
# third  parameter must be the id of the event (must be unique across all scripts)
# evrything else is the log message
if [[ "$WTL_DIR" == "" ]] ; then
    echo "Missing WTL_DIR env var. FATAL"
    exit 1
fi

wtl-log () {
    SCRIPT_NAME=$1 ; shift
    SCRIPT_FILENAME=$(basename $SCRIPT_NAME)
    LOG_LEVEL=$1   ; shift
    EVENT_ID=$1    ; shift
    LOG_MSG=$@
    case $LOG_LEVEL in
        "0")
            echo -e -n "\e[31mEmergency\e[0m"
        ;;
        "1")
            echo -e -n "\e[32mAlert\e[0m"
        ;;
        "2")
            echo -e -n "\e[32mCritical\e[0m"
        ;;
        "3")
            echo -e -n "\e[34mError\e[0m"
        ;;
        "4")
            echo -e -n "\e[34mWarning\e[0m"
        ;;
        "5")
            echo -e -n "\e[34mNotice\e[0m"
        ;;
        "6")
            echo -e -n "\e[34mInformational\e[0m"
        ;;
        "7")
            echo -e -n "\e[37mDebug\e[0m"
        ;;
        *)
            echo -e -n "\e[93mUNKNOWN\e[0m"
        ;;
    esac
    echo -n ": "
    echo $SCRIPT_FILENAME" > "$LOG_MSG
    if test -d $WTL_HOOKS"/"$EVENT_ID ; then
        ls $WTL_HOOKS"/"$EVENT_ID | sort | while read file ; do
            echo $file
            find $WTL_HOOKS"/"$EVENT_ID -type f -name $file -exec sh -c "echo 'Running hook: '{} ; {}" \;
        done
    fi
}

if [[ $(basename $0) == "wtl-log" ]] ; then
    SCRIPT_NAME=$1 ; shift
    LOG_LEVEL=$1   ; shift
    EVENT_ID=$1    ; shift
    LOG_MSG=$@
    wtl-log "$SCRIPT_NAME" "$LOG_LEVEL" "$EVENT_ID" "$LOG_MSG"
fi
